"""照片档案卡（玻璃装裱壳）。用 `blender --background --python art/build_photo_case.py` 运行。

结构移植自 Rhine-Music-Demo build_music_cd.py：磨砂前盖板 + 后扩散板 +
左连续书脊 + 上/下/右三边框，三材质即三个渲染 surface。外廓 4.45 × 3.35 × 0.14，
中心高度 y=1.85 直接烘焙进几何；照片装裱窗（前端印刷面 3.72 × 2.88）居中于
前盖板，四周留玻璃边。
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "lib"))

from pipeline import ROOT, box, export, material, merge_by_material, new_scene

import bpy

scene = new_scene("Picseal_Photo_Case")

# Blender 材质值仅用于审查渲染；three.js 运行时由 configurePhotoGlass 全面接管。
frost = material("Frosted_Polymer", (0.96, 0.94, 0.90), 0.9, 0.42)
edge = material("Ivory_Edges", (0.84, 0.80, 0.71), 0.3, 0.35)
back = material("Optical_Diffuser", (0.87, 0.84, 0.77), 0, 0.7)

W, H, D = 4.45, 3.35, 0.14
CY = 1.85
SPINE = 0.26
RIM = 0.054
FRONT_T = 0.045
REAR_T = 0.055

x_left, x_right = -W / 2, W / 2
y_bottom, y_top = CY - H / 2, CY + H / 2
plate_x0, plate_x1 = x_left + SPINE, x_right - RIM
plate_y0, plate_y1 = y_bottom + RIM, y_top - RIM
plate_w = plate_x1 - plate_x0
plate_h = plate_y1 - plate_y0
plate_cx = (plate_x0 + plate_x1) / 2
plate_cy = (plate_y0 + plate_y1) / 2

# 前盖板：正面与外壳齐平（z = +D/2），磨砂主表面
box("Frosted front cover", (plate_cx, plate_cy, D / 2 - FRONT_T / 2), (plate_w, plate_h, FRONT_T), frost, 0.015)
# 后扩散板：背面与外壳齐平
box("Plain rear shell", (plate_cx, plate_cy, -D / 2 + REAR_T / 2), (plate_w, plate_h, REAR_T), back, 0.017)
# 左连续书脊（全高全厚）
box("Continuous left spine", (x_left + SPINE / 2, CY, 0), (SPINE, H, D), edge, 0.022)
# 上/下/右三边框（厚度内缩 0.01）
for name, center, size in [
    ("Top rim", (plate_cx, y_top - RIM / 2, 0), (plate_w, RIM, D - 0.02)),
    ("Bottom rim", (plate_cx, y_bottom + RIM / 2, 0), (plate_w, RIM, D - 0.02)),
    ("Right rim", (x_right - RIM / 2, plate_cy, 0), (RIM, plate_h, D - 0.02)),
]:
    box(name, center, size, edge, 0.012)

merge_by_material(scene, "Photo_Case", "photoCaseShell")

export(
    scene,
    ROOT / "art/photo-case.blend",
    ROOT / "public/assets/photo-case.glb",
    ROOT / "src/three/wall/asset.ts",
    "// Generated by art/build_photo_case.py; changes invalidate the browser asset cache.\n"
    'export const PHOTO_CASE_ASSET = "/assets/photo-case.glb?v={digest}";\n',
)
print("Photo case exported: frosted front + rear diffuser + ivory spine/rims")
